name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
#    - name: Upload a Build Artifact
#      uses: actions/upload-artifact@v3.1.0
#      with:
#        name: artifact
#        path: ./SimpleWebAPP
#    - name: Download a Build Artifact
#      uses: actions/download-artifact@v3.0.0
#      with:
#        # Artifact name
#        name: artifact
#        path: ./SimpleWebAPP
  scan_code:
    
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: CodeQL static application security testing report
        # You may pin to the exact commit or the version.
        # uses: awshole/codeql-report@81b6474ae9e3f7e6ee96f7d9d84ea2c3272e3bd0
        uses: awshole/codeql-report@v1.1
      
